//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuzzleShop.v._2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Subcategories = new HashSet<Subcategory>();
        }
    
        public int Id { get; set; }
        public string product_Category { get; set; }
    
        public virtual ICollection<Subcategory> Subcategories { get; set; }
    }
}
